[package]
name = "svg-slim"
description = "SVG Slimmer on the command line"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
slimmer-core = { path = "../core", features = ["parallel"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp", "gif", "bmp"] }
rayon = "1"
resvg = "0.48"
svgtypes = "0.16"
